version: '3'
services:
  ingress:
    image: chickaree/ingress
    restart: always
    links:
      - web
    networks:
      - default
      - ingress
    environment:
        VIRTUAL_HOST: 'chickar.ee,origin.chickar.ee,www.chickar.ee'
        LETSENCRYPT_HOST: 'chickar.ee,origin.chickar.ee,www.chickar.ee'
  web:
    restart: always
    volumes:
      - database:/app/data
networks:
  ingress:
    external:
      name: ingress
volumes:
  database:
