name: Build

on: [push]

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: 'Deploy to Cloudflare'
      if: github.ref == 'refs/heads/master'
      uses: cloudflare/wrangler-action@1.1.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
  docker:
    if: github.ref == 'refs/heads/master'
    needs: [static]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login ghcr.io -u chickaree --password ${{ secrets.GITHUB_TOKEN }}
      - run: docker build --tag ghcr.io/${GITHUB_REPOSITORY} .
      - run: docker push ghcr.io/${GITHUB_REPOSITORY}
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.19.7'
      - uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_URL }}
          k8s-secret: ${{ secrets.K8S_SECRET }}
      - run: kubectl set image statefulset/chickaree web=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${GITHUB_REPOSITORY})


